#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__


# source version dependent parts of the installation
global CHECK_ACTUAL_TEST_PATH CHECK_TESTSUITE_INSTALL_MODE

global check_name check_description check_needs check_functions
global check_root_access_needs check_category      
global check_use_installed_system check_init_level_procedure

# This file shows some check spezific things
set check_root_access_needs    "yes"
set check_name                 "arco_junit"
set check_category             "COMPATIBILITY SYSTEM L10N VERIFIED"
set check_description(0)       "executes the ARCo junit tests"
set check_needs                "arco_database_install"         ;# dependencies of this check (name of other check)
set check_needs                ""                         ;# dependencies of this check (name of other check)
set check_init_level_procedure "arco_junit_init_level"
set check_functions            ""                                     ;# functions to call (in order)

set check_setup_level_function "arco_junit_setup_level"
set check_cleanup_level_function "arco_junit_cleanup_level"

lappend check_functions "arco_junit_check"


proc arco_junit_init_level {} {
  global CHECK_ACT_LEVEL

   switch -- $CHECK_ACT_LEVEL {
      "0" {
         return 0
      }
   }
   return -1  ;# no other level else
}

proc arco_junit_setup_level {} {
   # clean the arco database (drop all objects)
   arco_clean_database 1
}

proc arco_junit_cleanup_level {} {
   #nothing to do, dbwriter is started up imediately after it is installed
}

proc arco_junit_check {} {
   global CHECK_USER
   global CHECK_PROTOCOL_DIR arco_config ts_config
   
   array set report {}   
   report_create "ARCO_junit_tests" report 1 0
   
   #  Write the configuration file for the tests
   #  Use the template from arco_source dir
   set cmd "sed"

   set cmd_args            ""
   set db_name             [get_database_name]
   set db_host             [get_database_host]
   set write_user          [get_arco_write_user]
   set write_user_pw       [get_arco_user_pwd]
   set read_user           [get_arco_read_user]
   set read_user_pw        [get_arco_user_pwd]
   set file_name           $CHECK_PROTOCOL_DIR/arco_junit_config.properties
   set db_tablespace       $arco_config(tablespace)
   set db_index_tablespace $arco_config(tablespace_index)
   set identifier          [get_database_type]
   set jdbc_driver         [get_jdbc_driver]
   set jdbc_url            [get_jdbc_url $db_name]
   set db_def              database/$identifier/dbdefinition.xml
   set db_schema           [get_database_schema]
   set foreign_key_suffix  [get_foreign_key_suffix]

   append cmd_args " -e 's%@@IDENTIFIER@@%${identifier}%g'"
   append cmd_args " -e 's%@@JDBC_DRIVER@@%${jdbc_driver}%g'"
   append cmd_args " -e 's%@@DB_NAME@@%${db_name}%g'"
   append cmd_args " -e 's%@@DB_HOST@@%${db_host}%g'"
   append cmd_args " -e 's%@@JDBC_URL@@%${jdbc_url}%g'"
   append cmd_args " -e 's%@@JDBC_USER@@%${write_user}%g'"
   append cmd_args " -e 's%@@JDBC_PASSWORD@@%${write_user_pw}%g'"
   
   append cmd_args " -e 's%@@READONLY_USER@@%${read_user}%g'"
   append cmd_args " -e 's%@@READONLY_USER_PWD@@%${read_user_pw}%g'"
   append cmd_args " -e 's%@@SCHEMA@@%${db_schema}%g'"
   append cmd_args " -e 's%@@TABLESPACE@@%${db_tablespace}%g'"
   append cmd_args " -e 's%@@TABLESPACE_INDEX@@%${db_index_tablespace}%g'"
   append cmd_args " -e 's%@@DB_DEFINITION_FILE@@%${db_def}%g'"
   append cmd_args " -e 's%@@FOREIGN_KEY_SUFFIX@@%${foreign_key_suffix}%g'"

   append cmd_args " $arco_config(arco_source_dir)/dbwriter/test/DBWriterTestConfig.properties.template"
   append cmd_args " > $file_name"

   set dbwriter_host $arco_config(dbwriter_host)

   report_add_message report "java build host is \"$dbwriter_host\""
   report_add_message report "Creating junit config file $file_name"
   report_add_message report "$dbwriter_host: $cmd $cmd_args"

   set output [start_remote_prog $dbwriter_host $CHECK_USER $cmd "$cmd_args"]
   if { $prg_exit_state != 0 } {
      report_add_message report "sed of DBWriterTestConfig.properties.template failed, exit state $prg_exit_state"
      report_add_message report "$output"
      report_finish report -1
      ts_log_severe "sed of DBWriterTestConfig.properties.template failed"
      return -1
   }
   
   set ant_options "-Ddbwriter.test.config_file=$file_name"
   append ant_options " -Duse.classpath.from.sge.root=true"
   append ant_options " -Dsge.root=$ts_config(product_root)"

   set res [arco_build $dbwriter_host "test" report $ant_options 180]
   
   if { $res != 0 } {
      report_add_message report "ARCo junit tests failed"
      report_finish report -1
      ts_log_severe "ARCo junit tests failed"
      return -1
   } else {
      report_add_message report "ARCo junit successfully executed"
      report_finish report 0
      return 0
   }
}

