#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

# define global variable in this namespace
global check_name 
global check_category
global check_description 
global check_needs
global check_functions 
global check_highest_level
global check_init_level_procedure
global check_root_access_needs
global env

# set check_root_access_needs "yes"


# define a level initialization procedure:
set check_init_level_procedure "file_parsing_init_level"

# define test's name and run level descriptions
set check_name            "file_parsing"
set check_category        "COMPATIBILITY SYSTEM L10N VERIFIED"
set check_highest_level   0
set check_description(0)  "Testing global, home and pwd request def. file, script and command line options"

# define test's dependencies
set check_needs           "init_core_system" 

# setup and cleanup functions
set check_setup_function "file_parsing_setup"
set check_cleanup_function "file_parsing_cleanup"

# define test's procedure order
set check_functions ""
lappend check_functions "file_parsing_N_option"
lappend check_functions "file_parsing_long_option"
lappend check_functions "file_parsing_C_option"

global file_parsing_request_test
global file_parsing_cluster_request_file
global file_parsing_home_request_file
global file_parsing_local_request_file
global file_parsing_job_host

proc file_parsing_init_level {} {
  global CHECK_ACT_LEVEL

  switch -- $CHECK_ACT_LEVEL {
     "0" {
         return 0
     } 
  } 

  return -1  ;# no other level else
}

# -------- local test procedures -----------------------------------------------



proc file_parsing_setup {} {
  global ts_config
  global env
  global CHECK_JOB_OUTPUT_DIR
  global file_parsing_cluster_request_file 
  global file_parsing_home_request_file
  global file_parsing_local_request_file
  global file_parsing_job_script
  global file_parsing_option_file
  global file_parsing_job_host
  global CHECK_USE_HUDSON
  
  if {$CHECK_USE_HUDSON == 1} {
     ts_log_config "Test is not supported in this parallel run due to the usage of \$HOME/.sgerequest file"
     return 99
  }
 
  set file_parsing_cluster_request_file "$ts_config(product_root)/$ts_config(cell)/common/sge_request"
  set file_parsing_home_request_file    "$env(HOME)/.sge_request"
  set file_parsing_local_request_file   "$CHECK_JOB_OUTPUT_DIR/.sge_request"
  set file_parsing_job_script           "$CHECK_JOB_OUTPUT_DIR/request_job.sh"
  set file_parsing_option_file          "$CHECK_JOB_OUTPUT_DIR/option_file"
  set file_parsing_job_host             [host_conf_get_suited_hosts]
}


proc create_job_script { option } {
   global CHECK_USER
   global file_parsing_job_script file_parsing_job_host

   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_job_script
   set script_path [get_binary_path $file_parsing_job_host "sh"]
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"#$script_path\" > $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"#$ $option\" >> $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"sleep 15\" >> $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "chmod" "755 $file_parsing_job_script"
   wait_for_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_job_script
   set output [start_remote_prog $file_parsing_job_host $CHECK_USER "cat" "$file_parsing_job_script"]
   ts_log_fine $output
   ts_log_fine "$file_parsing_job_script"
} 

#****** check/create_C_job_script() ********************************************
#  NAME
#     create_C_job_script() -- creates an script file for -C option testing 
#
#  SYNOPSIS
#     create_C_job_script { option { option2 "" } } 
#
#  FUNCTION
#     This procedure creates a little shell-script which can be used to test the
#     -C option of qsub.
#
#  INPUTS
#     option         - line which will be pasted in the script 
#     { option2 "" } - line which will be pasted in the script
#
#  EXAMPLE
#     ??? 
#
#  NOTES
#     The additional lines (option and option2) have to be prefixed by #$ or 
#     the prefix you set with -C 
#
#*******************************************************************************
proc create_C_job_script { option { option2 "" } } {
   global CHECK_USER
   global file_parsing_job_script file_parsing_job_host

   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_job_script
   set script_path [get_binary_path $file_parsing_job_host "sh"]
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"#$script_path\" > $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"$option\" >> $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"$option2\" >> $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"sleep 15\" >> $file_parsing_job_script"
   start_remote_prog $file_parsing_job_host $CHECK_USER "chmod" "755 $file_parsing_job_script"
   wait_for_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_job_script
   set output [start_remote_prog $file_parsing_job_host $CHECK_USER "cat" "$file_parsing_job_script"]
   ts_log_fine $output
   ts_log_fine "$file_parsing_job_script"
}

#****** check/create_option_file() *********************************************
#  NAME
#     create_option_file() -- creates an option file 
#
#  SYNOPSIS
#     create_option_file { option } 
#
#  FUNCTION
#     This procedure creates an option file which can used with -@ option
#
#  INPUTS
#     option - option which should be in the file
#
#  EXAMPLE
#     create_option_file "-N COPTION"
#
#*******************************************************************************
proc create_option_file { option } {
   global CHECK_USER
   global file_parsing_job_host file_parsing_option_file

   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_option_file
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "\"$option\" > $file_parsing_option_file"
   start_remote_prog $file_parsing_job_host $CHECK_USER "chmod" "755 $file_parsing_option_file"
   wait_for_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_option_file
   set output [start_remote_prog $file_parsing_job_host $CHECK_USER "cat" "$file_parsing_option_file"]
   ts_log_fine $output
   ts_log_fine "$file_parsing_option_file"
}
 
proc prepare_file_and_start_job { request_file_name option_parameter job_script { start_directory "" } { c_option "" } } {
   global file_parsing_cluster_request_file
   global file_parsing_home_request_file
   global file_parsing_local_request_file
   global CHECK_USER
   global file_parsing_job_host

   ts_log_fine "creating file $request_file_name on host $file_parsing_job_host"
   set script_path [get_binary_path $file_parsing_job_host "sh"]
   start_remote_prog $file_parsing_job_host $CHECK_USER "echo" "$option_parameter -e /dev/null -o /dev/null -S $script_path > $request_file_name"

   wait_for_remote_file $file_parsing_job_host $CHECK_USER $request_file_name

   ts_log_fine "request file: $request_file_name"

   ts_log_fine "submitting job $job_script from directory $start_directory"
   set return_value [submit_job "$c_option -l h=$file_parsing_job_host $job_script" 0 30 $file_parsing_job_host "" $start_directory]
   ts_log_fine "return value of submit_job: $return_value"
   return $return_value
}

#****** check/file_parsing_C_func() ********************************************
#  NAME
#     file_parsing_C_func() -- submitting a job with various flavours of -C ''
#
#  SYNOPSIS
#     file_parsing_C_func { option_parameter ex_name script_option1 
#     { script_option2 "" } { c_option "" } } 
#
#  FUNCTION
#     Submits a generated script with the given options. Waits till an job appears
#     with the expected name otherwise it fails.
#
#  INPUTS
#     option_parameter      - option parameter which is passed to sge-option files 
#     ex_name               - expected job-name after submission 
#     script_option1        - line which is pasted into the to be executed script
#     { script_option2 "" } - line which is pasted into the to be executed script
#     { c_option "" }       - paramter for job submission
#
#  RESULT
#     the job-id of the submitted job 
#
#  EXAMPLE
#     file_parsing_C_func "-N GLOBAL" "GLOBAL" "#$ -C '#?'" "#? -N COPTION"
#
#*******************************************************************************
proc file_parsing_C_func { option_parameter ex_name script_option1 { script_option2 "" } { c_option "" } } {
   global file_parsing_cluster_request_file file_parsing_home_request_file
   global file_parsing_job_script file_parsing_job_host
   global file_parsing_option_file
   global CHECK_USER

   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
   create_C_job_script $script_option1 $script_option2 

   ts_log_fine "global sge_request file"
   set back [prepare_file_and_start_job $file_parsing_cluster_request_file $option_parameter $file_parsing_job_script "" $c_option]
   
   if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
        return
    }       
    wait_for_jobstart $back $ex_name 30 1 1
   
   ts_log_fine "home directory .sge_request file"
   set back [prepare_file_and_start_job $file_parsing_home_request_file $option_parameter $file_parsing_job_script "" $c_option]
   
   if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
        return
    }       
    wait_for_jobstart $back $ex_name 30 1 1
}

proc file_parsing_C_option {} {
   global file_parsing_cluster_request_file
   global file_parsing_home_request_file
   global file_parsing_job_script file_parsing_job_host
   global file_parsing_option_file
   global CHECK_USER

   ts_log_fine "Testing -C '#?' ..."
   file_parsing_C_func "-N GLOBAL" "COPTION" "#? -N COPTION" "" "-C '#?'"

   ts_log_fine "Testing -C with -b y ..."
   file_parsing_C_func "-N GLOBAL" "GLOBAL" "#? -N COPTION" "" "-C '#?' -b y"

   ts_log_fine "Testing -C in script file ..."
   file_parsing_C_func "-N GLOBAL" "GLOBAL" "#$ -C '#?'" "#? -N COPTION"

   ts_log_fine "Testing -C '' to avoid parsing script-file ..."
   file_parsing_C_func "-N GLOBAL" "GLOBAL" "#$ -N COPTION" "" "-C ''"

   ts_log_fine "Testing option file parsing '-@' ..."
   create_option_file "-N COPTION"
   file_parsing_C_func "-N GLOBAL" "COPTION" "#$ -N COPTION2" "" "-C '' -@ $file_parsing_option_file"

   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_option_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file

}

proc file_parsing_N_option {} {
   global file_parsing_cluster_request_file
   global file_parsing_home_request_file
   global file_parsing_local_request_file CHECK_USER
   global file_parsing_job_script file_parsing_job_host

   set accounting_jobs ""

    ts_log_fine "Testing overwrite options ..."
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_local_request_file

    create_job_script ""
    
    ts_log_fine "global sge_request file"
    set option_parameter "-N GLOBAL"
    set back [ prepare_file_and_start_job $file_parsing_cluster_request_file $option_parameter $file_parsing_job_script]
    if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
    }       
    wait_for_jobstart $back "GLOBAL" 30 1 1
    lappend accounting_jobs $back


    ts_log_fine "home directory .sge_request file"
    set option_parameter "-N HOME"
    set back [ prepare_file_and_start_job $file_parsing_home_request_file $option_parameter $file_parsing_job_script]
    if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
    }       
    wait_for_jobstart $back "HOME" 30 1 1
 
    lappend accounting_jobs $back


    ts_log_fine "local directory .sge_request file"
    set option_parameter "-N LOCAL"
    set back [ prepare_file_and_start_job $file_parsing_local_request_file $option_parameter $file_parsing_job_script [file dirname $file_parsing_local_request_file ]]
    if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
    }       
    wait_for_jobstart $back "LOCAL" 30 1 1
    lappend accounting_jobs $back

    ts_log_fine "script options"
    set option_parameter "-N SCRIPT"
    create_job_script "$option_parameter"
    set back [ submit_job "-l h=$file_parsing_job_host $file_parsing_job_script" 1 60 $file_parsing_job_host]
    if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
    }       
    wait_for_jobstart $back "SCRIPT" 30 1 1

    lappend accounting_jobs $back


    ts_log_fine "command_line"
    set option_parameter "-N COMLINE"
    create_job_script ""
    set back [ submit_job "$option_parameter -l h=$file_parsing_job_host $file_parsing_job_script" 1 60 $file_parsing_job_host ]
    if { $back < 0 } {
        ts_log_severe "Could not start job with $option_parameter parameter"      
    }
    wait_for_jobstart $back "COMLINE" 30 1 1

    lappend accounting_jobs $back


   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_local_request_file

   
   wait_for_end_of_all_jobs 60

   foreach elem $accounting_jobs {
      set timeout_time [timestamp]
      incr timeout_time 120
      while { 1 } {
         after 1000
         ts_log_fine "try to get accounting info for job $elem ..."
         set result [get_qacct $elem qacct_info "" "" 0]
         ts_log_fine "result: $result"
         if { $result != 0 } {
            if { [timestamp] < $timeout_time } {
               continue
            } else {
               break
            }
         } else {
            break
         }
      } 
      if { $result != 0 } {
         ts_log_severe "No accounting information for job $elem available" 
      } else {
         set names [array names qacct_info]
         foreach name $names {
            ts_log_fine "$name: $qacct_info($name)"
         }
      }
   }


#
#  command-line overwrites sge_definition file
#  command-line overwrites embedded script options
#  emmbedded script overwrites sge_definition file
#
}

proc file_parsing_long_option_verify {back long case} {
   global ts_config

   if { $back < 0 } {
      ts_log_severe "Could not start job ($case)"      
   }  
}

proc file_parsing_long_option {} {
   global ts_config CHECK_USER
   global file_parsing_cluster_request_file
   global file_parsing_home_request_file
   global file_parsing_local_request_file
   global file_parsing_job_script file_parsing_job_host

   set accounting_jobs ""

    ts_log_fine "Testing overwrite options ..."

    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_local_request_file

    create_job_script ""
  
    ts_log_fine "creating lines with more than 4300 chars"
 
   set option_parameter ""
   for {set i 0} {$i < 80} {incr i} {
      append option_parameter "-N TEST_$i"
      for {set j 0} {$j < 50} {incr j} {
         append option_parameter "_"
      }
      append option_parameter " "
   }

    ts_log_fine "global sge_request file"
    set back [ prepare_file_and_start_job $file_parsing_cluster_request_file $option_parameter $file_parsing_job_script]
    file_parsing_long_option_verify $back 1 "global sge_request file"
    
    ts_log_fine "home directory .sge_request file"
    set back [ prepare_file_and_start_job $file_parsing_home_request_file $option_parameter $file_parsing_job_script]
    file_parsing_long_option_verify $back 1 "home directory .sge_request file"

    ts_log_fine "local directory .sge_request file"
    set back [ prepare_file_and_start_job $file_parsing_local_request_file $option_parameter $file_parsing_job_script [file dirname $file_parsing_local_request_file]]
    file_parsing_long_option_verify $back 1 "local directory .sge_request file"
    
    ts_log_fine "script options"
    create_job_script "$option_parameter"
    set back [ submit_job "-l h=$file_parsing_job_host $file_parsing_job_script" 0 60 $file_parsing_job_host]
    file_parsing_long_option_verify $back 1 "script options"

    ts_log_fine "command_line"
    create_job_script ""
    set back [ submit_job "$option_parameter -l h=$file_parsing_job_host $file_parsing_job_script" 0 60 $file_parsing_job_host]
    file_parsing_long_option_verify $back 1 "command_line"

    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_local_request_file

    create_job_script ""
  
    ts_log_fine "creating lines with more than 2023 chars"
 
   set option_parameter ""
   for {set i 0} {$i < 40} {incr i} {
      append option_parameter "-N TEST_$i"
      for {set j 0} {$j < 50} {incr j} {
         append option_parameter "_"
      }
      append option_parameter " "
   }
    set opt_parameter "$option_parameter -N GLOBAL"
    ts_log_fine "global sge_request file"
    set back [ prepare_file_and_start_job $file_parsing_cluster_request_file $opt_parameter $file_parsing_job_script]
    file_parsing_long_option_verify $back 0 "global sge_request file"
    wait_for_jobstart $back "GLOBAL" 30  1 1
    lappend accounting_jobs $back

    ts_log_fine "home directory .sge_request file"
    set opt_parameter "$option_parameter -N HOME"
    set back [ prepare_file_and_start_job $file_parsing_home_request_file $opt_parameter $file_parsing_job_script]
    file_parsing_long_option_verify $back 0 "home directory .sge_request file"
    wait_for_jobstart $back "HOME" 30 1 1
    lappend accounting_jobs $back

    ts_log_fine "local directory .sge_request file"
    set opt_parameter "$option_parameter -N LOCAL"
    set back [ prepare_file_and_start_job $file_parsing_local_request_file $opt_parameter $file_parsing_job_script [file dirname $file_parsing_local_request_file]]
    file_parsing_long_option_verify $back 0 "local directory .sge_request file"
    wait_for_jobstart $back "LOCAL" 30 1 1
    lappend accounting_jobs $back

    ts_log_fine "script options"
    set opt_parameter "$option_parameter -N SCRIPT"
    create_job_script "$opt_parameter"
    set back [ submit_job "-l h=$file_parsing_job_host $file_parsing_job_script" 1 60 $file_parsing_job_host ]
    file_parsing_long_option_verify $back 0 "script options"
    wait_for_jobstart $back "SCRIPT" 30 1 1
    lappend accounting_jobs $back

    ts_log_fine "command_line"
    set opt_parameter "$option_parameter -N COMLIN"
    create_job_script ""
    set back [ submit_job "$opt_parameter -l h=$file_parsing_job_host $file_parsing_job_script" 1 60 $file_parsing_job_host ]
    file_parsing_long_option_verify $back 0 "command_line"
    wait_for_jobstart $back "COMLIN" 30 1 1
    lappend accounting_jobs $back

    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
    delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_local_request_file

    wait_for_end_of_all_jobs 60

    foreach elem $accounting_jobs {
      set timeout_time [timestamp]
      incr timeout_time 120
      while { 1 } {
         after 1000
         ts_log_fine "try to get accounting info for job $elem ..."
         set result [get_qacct $elem qacct_info "" "" 0]
         ts_log_fine "result: $result"
         if { $result != 0 } {
            if { [timestamp] < $timeout_time } {
               continue
            } else {
               break
            }
         } else {
            break
         }
      } 
      if { $result != 0 } {
         ts_log_severe "No accounting information for job $elem available" 
      } ;# else {
         # set names [array names qacct_info]
         # foreach name $names {
         #   ts_log_fine "$name: $qacct_info($name)"
         # }
      # }
   }

#
#  command-line overwrites sge_definition file
#  command-line overwrites embedded script options
#  emmbedded script overwrites sge_definition file
#
}


proc file_parsing_cleanup {} {
   
   global CHECK_USER file_parsing_job_host
   global file_parsing_local_request_file file_parsing_option_file
   global file_parsing_cluster_request_file file_parsing_home_request_file   

   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_option_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_cluster_request_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_home_request_file
   delete_remote_file $file_parsing_job_host $CHECK_USER $file_parsing_local_request_file

   delete_all_jobs
   wait_for_end_of_all_jobs 60
}

