#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

global check_functions

lappend check_functions "qdel_wc_job_range_list"


proc qdel_wc_job_range_list {} {
   global ts_config CHECK_USER CHECK_ACT_LEVEL

   if {$CHECK_ACT_LEVEL == 0} {
      set arguments "-N job1"
      set job_id1 [submit_job "$arguments $ts_config(product_root)/examples/jobs/sleeper.sh 100"]
      set arguments "-N job2"
      set job_id2 [submit_job "$arguments $ts_config(product_root)/examples/jobs/sleeper.sh 100"]
      set arguments "-N job3"
      set job_id3 [submit_job "$arguments $ts_config(product_root)/examples/jobs/sleeper.sh 100"]
      set arguments "-N job4"
      set job_id4 [submit_job "$arguments $ts_config(product_root)/examples/jobs/sleeper.sh 100"]
      wait_for_jobstart $job_id4 "job4" 60 1 1 
      
      # Now delete them using wc_job_range_list: job_id1,job2,job3 job_id4
      set output [start_sge_bin "qdel" "$job_id1,job2,job3 $job_id4"]
      puts "output= $output"
      
      set result1 [is_job_running $job_id1 "job1"]
      set result2 [is_job_running $job_id2 "job2"]
      set result3 [is_job_running $job_id3 "job3"]
      set result4 [is_job_running $job_id4 "job4"]
      
      if {$result1 != -1 || $result2 != -1 || $result3 != -1 || $result4 != -1} {
         add_proc_error "qdel_test_cmdline" -1 "jobs were not successfully deleted"
      }
   }
}
