#!/vol2/TCL_TK/glinux/bin/expect
#___INFO__MARK_BEGIN__
##########################################################################
#
#  The Contents of this file are made available subject to the terms of
#  the Sun Industry Standards Source License Version 1.2
#
#  Sun Microsystems Inc., March, 2001
#
#
#  Sun Industry Standards Source License Version 1.2
#  =================================================
#  The contents of this file are subject to the Sun Industry Standards
#  Source License Version 1.2 (the "License"); You may not use this file
#  except in compliance with the License. You may obtain a copy of the
#  License at http://gridengine.sunsource.net/Gridengine_SISSL_license.html
#
#  Software provided under this License is provided on an "AS IS" basis,
#  WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING,
#  WITHOUT LIMITATION, WARRANTIES THAT THE SOFTWARE IS FREE OF DEFECTS,
#  MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE, OR NON-INFRINGING.
#  See the License for the specific provisions governing your rights and
#  obligations concerning the Software.
#
#  The Initial Developer of the Original Code is: Sun Microsystems, Inc.
#
#  Copyright: 2001 by Sun Microsystems, Inc.
#
#  All Rights Reserved.
#
##########################################################################
#___INFO__MARK_END__

global qmod_num_help_lines
set qmod_num_help_lines 15

global check_functions
lappend check_functions    "qmod_verify"

#                                                             max. column:     |
#****** qmod/qmod_verify() ******
# 
#  NAME
#     qmod_verify -- ??? 
#
#  SYNOPSIS
#     qmod_verify { } 
#
#  FUNCTION
#     ??? 
#
#  INPUTS
#
#  RESULT
#     ??? 
#
#  EXAMPLE
#     ??? 
#
#  NOTES
#     ??? 
#
#  BUGS
#     ??? 
#
#  SEE ALSO
#     ???/???
#*******************************
proc qmod_verify {} {
   global ts_config CHECK_OUTPUT
   global test_queue 
  
   set output [start_sge_bin "qmod" "-verify -s $test_queue"]
   if {$prg_exit_state != 0} {
     add_proc_error "qmod_verify" -1 "exit state of \"qmod -verify -s $test_queue\" is not 0"
   }            
   
   set state [get_queue_state $test_queue]
   if {[string compare $state ""] != 0} {
      add_proc_error "qmod_verify" -1 "queue $test_queue is not in original state"
   }
}

